# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import puzzlebot_pb2 as puzzlebot__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in puzzlebot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PuzzlebotServiceStub(object):
    """Servicio principal del dashboard — solo streams de monitoreo + envío de waypoints
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.unary_stream(
                '/puzzlebot.PuzzlebotService/StreamTelemetry',
                request_serializer=puzzlebot__pb2.Empty.SerializeToString,
                response_deserializer=puzzlebot__pb2.TelemetryData.FromString,
                _registered_method=True)
        self.StreamCostmap = channel.unary_stream(
                '/puzzlebot.PuzzlebotService/StreamCostmap',
                request_serializer=puzzlebot__pb2.Empty.SerializeToString,
                response_deserializer=puzzlebot__pb2.CostmapData.FromString,
                _registered_method=True)
        self.StreamPath = channel.unary_stream(
                '/puzzlebot.PuzzlebotService/StreamPath',
                request_serializer=puzzlebot__pb2.Empty.SerializeToString,
                response_deserializer=puzzlebot__pb2.PathData.FromString,
                _registered_method=True)
        self.StreamNodeStatus = channel.unary_stream(
                '/puzzlebot.PuzzlebotService/StreamNodeStatus',
                request_serializer=puzzlebot__pb2.Empty.SerializeToString,
                response_deserializer=puzzlebot__pb2.NodeStatusList.FromString,
                _registered_method=True)
        self.StreamCamera = channel.unary_stream(
                '/puzzlebot.PuzzlebotService/StreamCamera',
                request_serializer=puzzlebot__pb2.Empty.SerializeToString,
                response_deserializer=puzzlebot__pb2.CameraFrame.FromString,
                _registered_method=True)
        self.SendWaypoints = channel.unary_unary(
                '/puzzlebot.PuzzlebotService/SendWaypoints',
                request_serializer=puzzlebot__pb2.WaypointList.SerializeToString,
                response_deserializer=puzzlebot__pb2.WaypointResponse.FromString,
                _registered_method=True)


class PuzzlebotServiceServicer(object):
    """Servicio principal del dashboard — solo streams de monitoreo + envío de waypoints
    """

    def StreamTelemetry(self, request, context):
        """Streams de datos salientes (servidor → cliente)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCostmap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamNodeStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWaypoints(self, request, context):
        """Comando unario: enviar lista de waypoints al robot
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PuzzlebotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=puzzlebot__pb2.Empty.FromString,
                    response_serializer=puzzlebot__pb2.TelemetryData.SerializeToString,
            ),
            'StreamCostmap': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCostmap,
                    request_deserializer=puzzlebot__pb2.Empty.FromString,
                    response_serializer=puzzlebot__pb2.CostmapData.SerializeToString,
            ),
            'StreamPath': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamPath,
                    request_deserializer=puzzlebot__pb2.Empty.FromString,
                    response_serializer=puzzlebot__pb2.PathData.SerializeToString,
            ),
            'StreamNodeStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamNodeStatus,
                    request_deserializer=puzzlebot__pb2.Empty.FromString,
                    response_serializer=puzzlebot__pb2.NodeStatusList.SerializeToString,
            ),
            'StreamCamera': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCamera,
                    request_deserializer=puzzlebot__pb2.Empty.FromString,
                    response_serializer=puzzlebot__pb2.CameraFrame.SerializeToString,
            ),
            'SendWaypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWaypoints,
                    request_deserializer=puzzlebot__pb2.WaypointList.FromString,
                    response_serializer=puzzlebot__pb2.WaypointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'puzzlebot.PuzzlebotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('puzzlebot.PuzzlebotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PuzzlebotService(object):
    """Servicio principal del dashboard — solo streams de monitoreo + envío de waypoints
    """

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/puzzlebot.PuzzlebotService/StreamTelemetry',
            puzzlebot__pb2.Empty.SerializeToString,
            puzzlebot__pb2.TelemetryData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCostmap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/puzzlebot.PuzzlebotService/StreamCostmap',
            puzzlebot__pb2.Empty.SerializeToString,
            puzzlebot__pb2.CostmapData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/puzzlebot.PuzzlebotService/StreamPath',
            puzzlebot__pb2.Empty.SerializeToString,
            puzzlebot__pb2.PathData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamNodeStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/puzzlebot.PuzzlebotService/StreamNodeStatus',
            puzzlebot__pb2.Empty.SerializeToString,
            puzzlebot__pb2.NodeStatusList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/puzzlebot.PuzzlebotService/StreamCamera',
            puzzlebot__pb2.Empty.SerializeToString,
            puzzlebot__pb2.CameraFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendWaypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/puzzlebot.PuzzlebotService/SendWaypoints',
            puzzlebot__pb2.WaypointList.SerializeToString,
            puzzlebot__pb2.WaypointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
